// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuA_FOr4kuKLzbYy-S8MQ57xPK-kn8qbs',
    appId: '1:611623666232:web:c9e7f3f0d0fb3c1bb79ccd',
    messagingSenderId: '611623666232',
    projectId: 'metature-technologies',
    authDomain: 'metature-technologies.firebaseapp.com',
    storageBucket: 'metature-technologies.appspot.com',
    measurementId: 'G-Q66BGKD0N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoaqrc3FfxpSPuX2V8UWjFagGfxsNzNmE',
    appId: '1:611623666232:android:8b833f3fadffd702b79ccd',
    messagingSenderId: '611623666232',
    projectId: 'metature-technologies',
    storageBucket: 'metature-technologies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmGeXGnCRE_JVZ3spjQq5zs_o073AKMhc',
    appId: '1:611623666232:ios:ee59a097f85b34cab79ccd',
    messagingSenderId: '611623666232',
    projectId: 'metature-technologies',
    storageBucket: 'metature-technologies.appspot.com',
    iosClientId: '611623666232-unqi9rhbrunh2nftg0dmm631kc1sf7fc.apps.googleusercontent.com',
    iosBundleId: 'com.metature.metature',
  );
}
